#!/bin/sh

ARGS=$(getopt -o s: --long size: -n virt-boot -- "$@")

if [ $? -ne 0 ]; then
	echo "usage: $myname <baseimage> <name>"
	exit 2
fi

eval set -- "$ARGS"

while :; do
	case "$1" in
		-s|--size)
			image_size="$2"
			shift 2
			;;
		--)	shift
			break
			;;
	esac
done

base_image="$1"
vol_name="$2"
shift 2

case $base_image in
	*/*)	:
		;;

	*)	echo "ERROR: base image must be specified as pool/volume" >&2
		exit 1
		;;
esac

base_image_pool=${base_image%/*}
base_image_name=${base_image#*/}

if [ -z "$image_size" ]; then
image_size=$(virsh vol-info $base_image_name $base_image_pool |
	awk '$1 == "Capacity:" {print $2}' |
	cut -f1 -d.)
fi

if ! virsh vol-key $base_image_name --pool $base_image_pool > /dev/null 2>&1; then
	echo "ERROR: base image $base_image does not exist" >&2
	exit 1
fi

(
virsh vol-delete $vol_name --pool $base_image_pool
) > /dev/null 2>&1

virsh vol-create-as $base_image_pool $vol_name ${image_size}G \
	--format qcow2 \
	--backing-vol $base_image_name \
	--backing-vol-format qcow2 >&2

echo $base_image_pool/$vol_name

