#!/bin/sh

boot_vol_bus=virtio

ARGS=$(getopt -o s:b:c:u:ik: --long ssh-key:,size:,import,bus,base-image:,config:,user-data: -n virt-boot -- "$@")

if [ $? -ne 0 ]; then
	echo "usage: $myname --base-image <baseimage> <name>"
	exit 2
fi

eval set -- "$ARGS"

: ${base_image:=$VIRT_BASE_IMAGE}

while :; do
	case "$1" in
		--bus)
			boot_vol_bus="$2"
			shift 2
			;;
		-b|--base-image)
			base_image="$2"
			shift 2
			;;
		-s|--image-size)
			base_image_size="$2"
			shift 2
			;;
		-c|--config-drive)
			config_image="$2"
			shift 2
			;;
		-k|--ssh-key)
			ssh_key="$2"
			shift 2
			;;
		-u|--user-data)
			user_data="$2"
			shift 2
			;;
		-i|--import)
			no_snapshot=1
			shift
			;;
		--)	shift
			break
			;;
	esac
done

dom_name=$1
shift

if [ "$ssh_key" ] && [ -f "$ssh_key" ]; then
	ssh_key_data=$(cat "$ssh_key")
fi

(
virsh destroy $dom_name
virsh undefine $dom_name
) > /dev/null 2>&1

if [ "$no_snapshot" = 1 ]; then
	boot_vol=$base_image
else
	boot_vol=$(virt-vol ${base_image_size:+-s $base_image_size} \
		$base_image $dom_name.qcow2)

	if [ $? -ne 0 ]; then
		echo "ERROR: failed to create boot volume" >&2
		exit 1
	fi
fi

if ! [ "$config_image" ]; then
	config_image=/tmp/${dom_name}-config.iso
	create-config-drive \
		-h $dom_name \
		${ssh_key:+-k $ssh_key} \
		${user_data:+-u $user_data} \
		$config_image
fi

virt-install -n $dom_name \
	--disk vol=$boot_vol,bus=$boot_vol_bus --import \
	--vnc --noautoconsole \
	${config_image:+--disk path=$config_image,device=cdrom} \
	"$@"

