#!/bin/sh

mac=$(virsh dumpxml $1 |
	xml2  |
	awk -F= '$1 == "/domain/devices/interface/mac/@address" {print $2; exit}')

ip=$(awk -vmac=$mac '$2 == mac {print $3}' /var/lib/libvirt/dnsmasq/default.leases )
echo $ip

