#!/bin/sh

ARGS=$(getopt -o r:67b: --long base-image: -n virt-boot -- "$@")

if [ $? -ne 0 ]; then
	echo "usage: $myname --base-image <baseimage> <name>"
	exit 2
fi

eval set -- "$ARGS"

while :; do
	case "$1" in
		-6)
			shift
			base_image=default/rhel-guest-image-6.6.qcow2
			;;
		-7)
			shift
			base_image=default/rhel-guest-image-7.0.qcow2
			;;
		-b|--base-image)
			base_image=$2
			shift 2
			;;
		-r)
			dom_mem=$2
			shift 2
			;;
		--)	shift
			break
			;;
	esac
done

vol_name=$1
shift

base_image_pool=${base_image%/*}
base_image_name=${base_image#*/}
base_image_cap=$(virsh vol-info $base_image_name $base_image_pool |
	awk '$1 == "Capacity:" {print $2}' |
	cut -f1 -d.)

(
virsh vol-delete $vol_name $base_image_pool
) > /dev/null 2>&1

virsh vol-create-as $base_image_pool $vol_name ${base_image_cap}G \
	--format qcow2 \
	--backing-vol $base_image_name \
	--backing-vol-format qcow2 >&2

echo $base_image_pool/$vol_name
